server:
  port: 8889

xxl:
  job:
    admin:
      #addresses: http://192.168.200.130:8888/xxl-job-admin
      addresses: http://localhost:8080/xxl-job-admin
    executor:
      appname: xxl-job-executor-sample
      port: 39999
